name: Build Visual Studio Project

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: GitHub Repository URL
        required: true
      commit:
        description: 'Commit or Tag to Checkout (Optional)'
        required: false
      project_file:
        description: .sln or .csproj file path (Optional)
        required: false
      msbuild_args:
        description: 'MSBuild Arguments (Optional)'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      run: |
        git clone ${{ github.event.inputs.repo_url }} temp_repo
        cd temp_repo

        $commitHash = git rev-parse HEAD
        echo "CURRENT_COMMIT=$commitHash" | Out-File -Append $env:GITHUB_ENV


    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Add dotnet to PATH
      uses: actions/setup-dotnet@v3

    - name: Find and Build Visual Studio Projects
      shell: pwsh
      run: |
        cd temp_repo
        msbuild.exe ${{ github.event.inputs.project_file }} /p:OutDir=output /p:Configuration=Release ${{ github.event.inputs.msbuild_args }}}

    - name: Set artifact name
      shell: pwsh
      run: |
        $repoName = ("${{ github.event.inputs.repo_url }}" -replace '^.*github\.com\/', '').Replace('/', '_')
        echo "REPO_NAME=$repoName" | Out-File -Append $env:GITHUB_ENV

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.project_path }}
        path: temp_repo/**/output/
        if-no-files-found: error

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.REPO_NAME }}@${{ github.event.inputs.commit || env.CURRENT_COMMIT }}
        body: |
          Repo URL: ${{ github.event.inputs.repo_url }}
          Project Path: ${{ github.event.inputs.project_path }}
          Build Target: ${{ github.event.inputs.build_target }}
          Commit or Tag: ${{ github.event.inputs.commit || env.CHECKED_OUT_COMMIT }}
        draft: false
        prerelease: false
        files: |
          temp_repo/**/output/*
