name: Build Visual Studio Project

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: GitHub Repository URL
        required: true
      project_path:
        description: .sln or .csproj file path (Optional)
        required: false
      build_target:
        description: 'MSBuild Target (Optional)'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      run: |
        git clone ${{ github.event.inputs.repo_url }} temp_repo
        cd temp_repo
        if (-not "${{ github.event.inputs.project_path }}") {
          echo "PROJECT_PATH=" >> $GITHUB_ENV
        } else {
          echo "PROJECT_PATH=${{ github.event.inputs.project_path }}" >> $GITHUB_ENV
        }

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Add dotnet to PATH
      uses: actions/setup-dotnet@v3

    - name: Find and Build Visual Studio Projects
      shell: pwsh
      run: |
        cd temp_repo
        $buildCmd = if ("${{ github.event.inputs.build_target }}") { "/t:${{ github.event.inputs.build_target }}" } else { "" }
        msbuild.exe $env:PROJECT_PATH /p:OutputPath=output /p:Configuration=Release $buildCmd

    - name: Set artifact name
      shell: pwsh
      run: |
        $repoName = ("${{ github.event.inputs.repo_url }}" -replace '^.*github\.com\/', '').Replace('/', '_')
        echo "REPO_NAME=$repoName" | Out-File -Append $env:GITHUB_ENV

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.project_path }}
        path: temp_repo/**/output/
        if-no-files-found: error
